### ISSUE TITLE
No provider for ThObject3D found in NodeInjector. 

### ISSUE THREAD

**Issue by Cuculcan** [demike/ngx-three#36]
Some time Im catch
 ERROR Error: NG0201: No provider for ThObject3D found in NodeInjector. Find more at https://angular.io/errors/NG0201
    at throwProviderNotFoundError (core.mjs:225:11)
    at notFoundValueOrThrow (core.mjs:3230:9)
    at lookupTokenUsingModuleInjector (core.mjs:3265:12)
    at getOrCreateInjectable (core.mjs:3300:12)
    at Module.ɵɵdirectiveInject (core.mjs:10135:12)
    at NodeInjectorFactory.RaycasterEventDirective_Factory [as factory] (ngx-three.mjs:398:99)
    at getNodeInjectable (core.mjs:3485:44)
    at instantiateAllDirectives (core.mjs:11092:27)
    at createDirectivesInstances (core.mjs:10563:5)
    at ɵɵelementStart (core.mjs:13716:9)

version: 0.24.0

**Comment by demike** [comment]
Did you create a custom component derived from ThObject3d? Because the you might be missing
this providers entry in your component:
https://github.com/demike/ngx-three/blob/ba2b6c08bcbbcf980732d7bcfdeb74e33c2a5ccd/projects/ngx-three/src/lib/generated/ThMesh.ts#L12

Of course replace the useExisting with your class.

If you can provide a minimal example i.e. on stackblitz
I can take a look
